### ISSUE TITLE
[UI] 검색 UI 구현 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/iOS_TestProject#2]
## Todo

- [x] 상단 - 로고/검색 Bar UI 구현 
- [x] 채용/기업 메뉴 탭 눌렀을 때 UI 변화 구현 
- [x] 하단 채용/기업 UI 구현
